# Generated by Django 3.1.5 on 2021-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerlog',
            name='headers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
