# Generated by Django 3.1.5 on 2021-01-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_squashed_0006_auto_20210106_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listener',
            options={'ordering': ['user'], 'permissions': (('view_all_listeners', 'Can view all webhook listeners'),)},
        ),
    ]
